//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoteTaking.Wcf.TestClient.UserServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UserServiceReference.IUserService")]
    public interface IUserService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/Create", ReplyAction="http://tempuri.org/IUserService/CreateResponse")]
        NoteTaking.Wcf.Contracts.Models.UserDto Create(NoteTaking.Wcf.Contracts.Models.UserCreateDto userCreateDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/Create", ReplyAction="http://tempuri.org/IUserService/CreateResponse")]
        System.Threading.Tasks.Task<NoteTaking.Wcf.Contracts.Models.UserDto> CreateAsync(NoteTaking.Wcf.Contracts.Models.UserCreateDto userCreateDto);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserServiceChannel : NoteTaking.Wcf.TestClient.UserServiceReference.IUserService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserServiceClient : System.ServiceModel.ClientBase<NoteTaking.Wcf.TestClient.UserServiceReference.IUserService>, NoteTaking.Wcf.TestClient.UserServiceReference.IUserService {
        
        public UserServiceClient() {
        }
        
        public UserServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public NoteTaking.Wcf.Contracts.Models.UserDto Create(NoteTaking.Wcf.Contracts.Models.UserCreateDto userCreateDto) {
            return base.Channel.Create(userCreateDto);
        }
        
        public System.Threading.Tasks.Task<NoteTaking.Wcf.Contracts.Models.UserDto> CreateAsync(NoteTaking.Wcf.Contracts.Models.UserCreateDto userCreateDto) {
            return base.Channel.CreateAsync(userCreateDto);
        }
    }
}
